version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: iconikio/mini-mam-api-gateway:main
    ports:
      - "8000:8000"
      - "9090:9090"  # Metrics port
    environment:
      - FLASK_ENV=production
      - ASSETS_SERVICE_URL=http://assets-service:8001
      - FILES_SERVICE_URL=http://files-service:8002
      - TRANSCODE_SERVICE_URL=http://transcode-service:8003
      - SEARCH_SERVICE_URL=http://search-service:8004
      - API_GATEWAY_METRICS_PORT=9090
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - USER_PASSWORD=${USER_PASSWORD}
    depends_on:
      - assets-service
      - files-service
      - transcode-service
      - search-service
    networks:
      - microservices-network

  # Assets Service
  assets-service:
    image: iconikio/mini-mam-assets-service:main
    ports:
      - "8001:8001"
      - "9091:9091"  # Metrics port
    environment:
      - FLASK_ENV=production
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - FILES_SERVICE_URL=http://files-service:8002
      - SECRET_KEY=${SECRET_KEY}
      - ASSETS_SERVICE_METRICS_PORT=9091
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    depends_on:
      - postgres
      - files-service
    networks:
      - microservices-network

  # Files Service
  files-service:
    image: iconikio/mini-mam-files-service:main
    ports:
      - "8002:8002"
      - "9092:9092"  # Metrics port
    environment:
      - FLASK_ENV=production
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - SECRET_KEY=${SECRET_KEY}
      - FILES_SERVICE_METRICS_PORT=9092
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    depends_on:
      - postgres
    networks:
      - microservices-network

  # Transcode Service
  transcode-service:
    image: iconikio/mini-mam-transcode-service:main
    ports:
      - "8003:8003"
      - "9094:9094"  # Metrics port
    environment:
      - FLASK_ENV=production
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - OUTPUT_FOLDER=/app/transcoded
      - TEMP_FOLDER=/app/temp
      - SECRET_KEY=${SECRET_KEY}
      - TRANSCODE_SERVICE_METRICS_PORT=9094
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    volumes:
      - transcode-output:/app/transcoded
      - transcode-temp:/app/temp
    depends_on:
      - postgres
    networks:
      - microservices-network

  # Search Service
  search-service:
    image: iconikio/mini-mam-search-service:main
    ports:
      - "8004:8004"
      - "9093:9093"  # Metrics port
    environment:
      - FLASK_ENV=production
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - SECRET_KEY=${SECRET_KEY}
      - SEARCH_SERVICE_METRICS_PORT=9093
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    depends_on:
      - postgres
    networks:
      - microservices-network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_MULTIPLE_DATABASES=assets_db,files_db,transcode_db,search_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - microservices-network

  # Frontend React Application
  frontend:
    image: iconikio/mini-mam-frontend:main
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:80
      - GENERATE_SOURCEMAP=false
    depends_on:
      - api-gateway
    networks:
      - microservices-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
      - assets-service
      - files-service
      - transcode-service
      - search-service
    networks:
      - microservices-network

volumes:
  postgres-data:
  file-uploads:
  transcode-output:
  transcode-temp:

networks:
  microservices-network:
    driver: bridge 